name: Synthesis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  synthesis:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install OSS-CAD-Suite
      uses: YosysHQ/setup-oss-cad-suite@v3

    - name: Run Yosys Synthesis
      run: |
        make synth  
